services:
  - type: web
    name: telegram-simple-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: GROUP_NAME
        value: Gp Name 
